"""AG-001 / AG-002: Agent observation, decision, and contract dataclasses.

These types allow pipeline stages to emit structured observations and
propose next-step decisions without coupling to LLM calls.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal


# ---------------------------------------------------------------------------
# AG-001: AgentObservation / AgentDecision
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class AgentObservation:
    """Snapshot produced by a pipeline stage after one run.

    AG-001 — every stage that completes (or fails) documents what it saw
    and what changed.
    """

    stage: str
    run_id: str
    artifact_paths: list[str] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    sample_records: list[dict[str, Any]] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    budget: dict[str, Any] = field(default_factory=dict)


RiskLevel = Literal["low", "medium", "high"]


@dataclass(frozen=True)
class AgentDecision:
    """A structured next-step proposal emitted by a stage or coordinator.

    AG-001 — captures *what* should happen next, *why*, and the
    associated risk / human-approval requirements.
    """

    action_type: str
    target_tool: str
    params: dict[str, Any] = field(default_factory=dict)
    reason: str = ""
    expected_effect: str = ""
    risk_level: RiskLevel = "low"
    requires_human_approval: bool = False


# ---------------------------------------------------------------------------
# Supporting contracts
# ---------------------------------------------------------------------------

ToolStatus = Literal["ok", "error", "blocked"]


@dataclass(frozen=True)
class ToolResult:
    """Result envelope returned by a tool execution.

    Separates success / error / blocked channels so callers can
    pattern-match without inspecting unstructured payloads.
    """

    status: ToolStatus = "ok"
    artifacts: list[str] = field(default_factory=list)
    metrics_delta: dict[str, Any] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)


StageGate = Literal["pass", "needs_review", "blocked"]


@dataclass(frozen=True)
class StageScore:
    """Quantitative + qualitative assessment of a stage's output quality.

    Used by review / scoring nodes to gate progression.
    """

    score: float = 0.0  # 0–100
    gate: StageGate = "pass"
    blocking_issues: list[str] = field(default_factory=list)
    recommended_actions: list[str] = field(default_factory=list)

    def __post_init__(self):
        if not (0.0 <= self.score <= 100.0):
            raise ValueError(f"score must be 0–100, got {self.score}")


@dataclass(frozen=True)
class ConfigPatchProposal:
    """A proposed change to a configuration value, surfaced for review.

    Generated by agents that detect misconfiguration or tuning
    opportunities.
    """

    target_config: str
    changes: dict[str, Any] = field(default_factory=dict)
    reason: str = ""
    risk_level: RiskLevel = "low"
    requires_approval: bool = True


# ---------------------------------------------------------------------------
# Builder functions
# ---------------------------------------------------------------------------


def build_agent_observation(
    stage: str,
    run_id: str,
    *,
    artifact_paths: list[str] | None = None,
    metrics: dict[str, Any] | None = None,
    sample_records: list[dict[str, Any]] | None = None,
    errors: list[str] | None = None,
    budget: dict[str, Any] | None = None,
) -> AgentObservation:
    """Build an AgentObservation with defaults applied for every field.

    Returns:
        Frozen AgentObservation instance.
    """
    return AgentObservation(
        stage=stage,
        run_id=run_id,
        artifact_paths=list(artifact_paths) if artifact_paths else [],
        metrics=dict(metrics) if metrics else {},
        sample_records=list(sample_records) if sample_records else [],
        errors=list(errors) if errors else [],
        budget=dict(budget) if budget else {},
    )


def build_agent_decision(
    action_type: str,
    target_tool: str,
    params: dict[str, Any] | None = None,
    reason: str = "",
    *,
    expected_effect: str = "",
    risk_level: RiskLevel = "low",
    requires_human_approval: bool = False,
) -> AgentDecision:
    """Build an AgentDecision with explicit fields.

    Returns:
        Frozen AgentDecision instance.
    """
    return AgentDecision(
        action_type=action_type,
        target_tool=target_tool,
        params=dict(params) if params else {},
        reason=reason,
        expected_effect=expected_effect,
        risk_level=risk_level,
        requires_human_approval=requires_human_approval,
    )


# ---------------------------------------------------------------------------
# AG-002: No Suitable Tool handling
# ---------------------------------------------------------------------------


def build_needs_user_action_decision(
    stage: str,
    reason: str,
    suggested_actions: list[str] | None = None,
    *,
    risk_level: RiskLevel = "medium",
) -> AgentDecision:
    """AG-002 — Emit a decision that requires a human operator to act.

    Used when no automated tool can handle the situation and the
    pipeline must pause for manual intervention.

    Args:
        stage: Pipeline stage that detected the need for human action.
        reason: Why automation cannot proceed.
        suggested_actions: Concrete steps the operator should take.
        risk_level: Defaults to "medium" for unattended pipelines.

    Returns:
        AgentDecision with ``action_type="needs_user_action"`` and
        ``requires_human_approval=True``.
    """
    actions = list(suggested_actions) if suggested_actions else []
    return AgentDecision(
        action_type="needs_user_action",
        target_tool="user_intervention",
        params={"stage": stage, "suggested_actions": actions},
        reason=reason,
        expected_effect="Pipeline resolves blockage after human operator acts on the suggested actions.",
        risk_level=risk_level,
        requires_human_approval=True,
    )
